2021-05-03 13:07:13,368 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=59227): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee24c2c940>: Failed to establish a new connection: [Errno 111] В соединении отказано'))
2021-05-03 13:07:13,474 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=59227): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee24c4b1f0>: Failed to establish a new connection: [Errno 111] В соединении отказано'))
2021-05-03 13:07:13,578 - ERROR - HTTPConnectionPool(host='127.0.0.1', port=59227): Max retries exceeded with url: /ready (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fee24c4b9d0>: Failed to establish a new connection: [Errno 111] В соединении отказано'))
